### ISSUE TITLE
ta_test aborts computation with ```fatal error: in "distributed_storage_suite/array_operator": memory access violation```, keeps running

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/tiledarray#100]
On the Debian/Ubuntu autobuilders, running the tiledarray test suite results in a message ```fatal error: in "distributed_storage_suite/array_operator": memory access violation at address: 0xXXXXXXXXXXXX: no mapping at fault address```; afterwards, the CPU load is going down from 100% per core to around 5% but ta_test keeps running, eventually running into a timeout.

See e.g. https://launchpadlibrarian.net/289062917/buildlog_ubuntu-yakkety-amd64.tiledarray_0.4.4-2_BUILDING.txt.gz and https://tests.reproducible-builds.org/debian/rb-pkg/testing/armhf/tiledarray.html - I've verified it still happens with 0.6.0 as well. The last upload of tiledarray to Debian this summer built fine (see https://buildd.debian.org/status/fetch.php?pkg=tiledarray&arch=amd64&ver=0.4.4-2&stamp=1472145648) so apparently something changed in the toolchain.

Is this a known issue and/or does a work-around/fix exist?

**Comment by mbanck** [comment]
One major difference between the last good build this summer and now is that openmpi got updated from 1.10 to 2.0.

**Comment by mbanck** [comment]
I've switched MADNESS and TA to MPICH, but the error remains.

**Comment by evaleev** [comment]
This is not a known issue.

To help reproduce: could you specify how madness (libmadness-dev?) is compiled?

**Comment by mbanck** [comment]
MADNESS is taken from Debian unstable, see https://buildd.debian.org/status/fetch.php?pkg=madness&arch=amd64&ver=0.10.1~gite4aa500e-3&stamp=1482856130 

In particular:

```
gfortran-6 amd64 6.2.1-7 [6910 kB]
libblas-dev amd64 3.6.1-2 [18.9 kB]
liblapack-dev amd64 3.6.1-2 [1977 kB]
libmpich-dev amd64 3.2-7 [1199 kB]
[...]
Toolchain package versions: binutils_2.27.51.20161220-1 dpkg-dev_1.18.18 g++-6_6.2.1-7 gcc-6_6.2.1-7 libc6-dev_2.24-8 libstdc++-6-dev_6.2.1-7 libstdc++6_6.2.1-7 linux-libc-dev_4.8.15-1
[...]
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-optimal "LIBS=-Wl,-z,relro -lmpich -lcr -lrt -lpthread"
```
Where $LIBS is set to "pkg-config --libs mpi" (using MPICH's .pc file).

Note that I'm only using the static MADNESS libraries as (AFAIK) there's no API guarantees at this point for shared libraries.

Also, the installed MADNESS cmake module is making trouble, I get

```
CMake Warning at external/madness.cmake:19 (find_package):
  Could not find a configuration file for package "MADNESS" that is
  compatible with requested version "0.10.1".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/madness/madness-config.cmake, version: unknown
```

So I have to remove the version.  The resulting madness-config.cmake can be seen here: http://paste.debian.net/905159/

**Comment by evaleev** [comment]
@mbanck the cmake files installed when compiling madness with autotools are possibly (or probably) broken, we never test this mode since cmake build is much more robust. unfortunately fixing it may not be worth the effort.

so it seems that madness is compiled without TBB support, correct? And this is gcc 6.2.1?

**Comment by mbanck** [comment]
Yes, no TBB, I haven't looked into that yet but I am happy to include it if all it means is adding libtbb-dev as a build-time dependency. And yes, gcc 6.2.1, though possibly the Debian/Ubuntu packages pull some additional fixes.

**Comment by justusc** [comment]
TBB should be used by default

**Comment by mbanck** [comment]
The version in Debian/Ubuntu is 4.3, which is apparently too old for MADNESS.

**Comment by evaleev** [comment]
tests do not need TBB. Most recent Intel or open-source TBB is 2017 (before that they used the usual versioning system e.g. 4.4.x ).

@mbanck which version of mpich did you use and how was it compiled?

**Comment by mbanck** [comment]
MPICH is 3.2, again Debian testing/unstable package. As the issue also happens with OpenMPI, I am not sure MPICH is the culprit, but it was configured like this: 

Configuring MPICH version 3.2 with  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--enable-shared' '--prefix=/usr' '--enable-fortran=all' '--disable-rpath' '--disable-wrapper-rpath' '--sysconfdir=/etc/mpich' '--libdir=/usr/lib/x86_64-linux-gnu' '--includedir=/usr/include/mpich' '--docdir=/usr/share/doc/mpich' '--with-hwloc-prefix=system' '--enable-checkpointing' '--with-hydra-ckpointlib=blcr' 'CPPFLAGS=' 'CFLAGS=' 'CXXFLAGS=' 'FFLAGS=' 'FCFLAGS=' 'build_alias=x86_64-linux-gnu' 'MPICHLIB_CFLAGS=-g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong -Wformat -Werror=format-security' 'MPICHLIB_CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'MPICHLIB_CXXFLAGS=-g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong -Wformat -Werror=format-security' 'MPICHLIB_FFLAGS=-g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong' 'MPICHLIB_FCFLAGS=-g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong' 'LDFLAGS=-Wl,-z,relro' 'FC=gfortran' 'F77=gfortran' 'MPILIBNAME=mpich'

according to https://buildd.debian.org/status/fetch.php?pkg=mpich&arch=amd64&ver=3.2-7&stamp=1470826142

**Comment by evaleev** [comment]
@mbanck update: reproduced the bug, with and without TBB, seems to occur in DistributedStorage<int>::get(idx) when idx refers to a remote element. nothing interesting from valgrind.

similar configuration on OS X (gcc 6.1 + mpich 3.2 + tbb) is OK.

**Comment by mbanck** [comment]
Glad that you managed to reproduce it. By the way, I hacked out that particular test, but several more had the same issue, so at some point I gave up.  The ones I skipped were:

```
BOOST_AUTO_TEST_CASE( array_operator )
BOOST_AUTO_TEST_CASE( tile_get_and_set_w_value )
BOOST_AUTO_TEST_CASE( tile_get_and_set_w_future )
BOOST_AUTO_TEST_CASE( tile_iterator_w_value )
BOOST_AUTO_TEST_CASE( tile_iterator_w_future )
```

Hopefully that is all the same cause.

**Comment by evaleev** [comment]
yes, I think something fundamental is broken on this platform

**Comment by evaleev** [comment]
the culprit is ASLR, it needs to be off.

**Comment by mbanck** [comment]
My guess would be it's https://wiki.ubuntu.com/SecurityTeam/PIE as that is a recent addition (16.10). To be clear, ASLR (or PIE) needs to be disabled in MADNESS, right? (and possibly in TA as well)

**Comment by evaleev** [comment]
Yes, MADNESS runtime (and all of its users, by extension) requires non-PIE. This is a MADNESS issue and will be resolved for non-OS-X platforms by an updated MADNESS release.

**Comment by evaleev** [comment]
@mbanck adding -no-pie linker flag manually resolves the issue

**Comment by justusc** [comment]
This option should definitely be added to a toolchain file, and in MADNESS as well. When this issue popped up in OS X, it caused major problems for a lot of users until I modified the configure script.

**Comment by evaleev** [comment]
madness commit f625ad5 resolves this and there will be no need for these flags in toolchain files once we bump madness tag.

Unfortunately, on Ubuntu this breaks shared library builds of libtiledarray due to (I suspect) a bug in gcc (it tries to link in crt1.o into libtiledarray.so when -no-pie is given, even though this is not an executable) and lack of support in CMake for the "right thing" (ability to declare that any executable linking in libMADworld must be linked with a non-PIE flag). I filed a request for the latter on CMake bug tracker.

**Comment by justusc** [comment]
OK thanks for the info. Maybe it would be better to try setting CMAKE_POSITION_INDEPENDENT_CODE to FALSE, rather than setting the linker flags manually. This would set the default value for the POSITION_INDEPENDENT_CODE target property. If it does not work we could at least file a bug report with CMake, and maybe get some more eyes looking at the problem.

https://cmake.org/cmake/help/v3.0/prop_tgt/POSITION_INDEPENDENT_CODE.html

**Comment by evaleev** [comment]
Actually this is not enough since in Ubuntu/Debian gcc will create PIE *by default* (this is something you can configure gcc to do by default) which means to disable it we need to add a linker flag ... setting POSITION_INDEPENDENT_CODE property to OFF does not do that as far as I can tell.

**Comment by justusc** [comment]
> Unfortunately, on Ubuntu this breaks shared library builds of libtiledarray due to (I suspect) a bug in gcc (it tries to link in crt1.o into libtiledarray.so when -no-pie is given, even though this is not an executable) and lack of support in CMake for the "right thing" (ability to declare that any executable linking in libMADworld must be linked with a non-PIE flag). I filed a request for the latter on CMake bug tracker.

This is probably due to the fact that the version of GCC used in Ubuntu is a modified version (per the link provided by @mbanck https://wiki.ubuntu.com/SecurityTeam/PIE). I do not doubt your analysis of the situation, but it feels very unsatisfying. Especially since the it breaks shared libraries.

**Comment by evaleev** [comment]
let's see if kitware team is responsive: https://gitlab.kitware.com/cmake/cmake/issues/16532

**Comment by justusc** [comment]
I read the documentation for the PIC flag in CMake, and I agree that it was not well thought out.

Your bug report reminded me that the standard build procedure for shared libraries is to add `-fPIC` (or similar) when compiling the object files. This is not necessary when compiling static object files, except when ASLR is turned on, in which case `-fPIC` is added by default. The PIC in shared libraries does not make a difference with respect to ASLR; the address randomization occurs on the executable side. That is, the if the executable is position independent and ALSR is enabled, the shared library will also be loaded at a random address. However, if PIC has been disabled in the executable, the shared library will always be loaded at the same position. OS X has been using ASLR for years without the need to turn off PIC on shared libraries.

So I think the correct way to handle this is to add -no-pie to static libraries and executables, but not shared libraries.

**Comment by evaleev** [comment]
@justusc yes, cmake's handling of PIC is broken. I think this is likely due to the widely-held misconception that PIC for object files and for the executable are related.

**Comment by evaleev** [comment]
btw, the filed issue with the cmake team is only step 1: this will allow us to create shared libtiledarray.so on debian/ubuntu again (this still requires manual linker flag manipulation). Step 2 is to have them fix POSITION_INDEPENDENT_CODE so that it's usable ... only then we'll be able to get rid of the linker flag voodoo.

**Comment by evaleev** [comment]
added another CMake issue to help with this: https://gitlab.kitware.com/cmake/cmake/issues/16561
