### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by DJDDDM** [ValeevGroup/tiledarray#149]
Hi,
I am unable to find the documentation for how to limit the sum, such that it doesnt go over the whole matrix but only over a part of it (for a quantum chemical example: only the occupied part of the Transformationmatrix to get the Densitymatrix (P = C[:,0:NOCC]*C[:,0:NOCC].transpose ).
And I am unable to find the documentation for  doing operations like solving the Eigenvalueproblem. (Quantum chemical example: Diagonalisation of the Fockmatrix).
If these dont exist, please add them.
If these exist please show me and make it more clear in the wiki.
thx

**Comment by justusc** [comment]
@DJDDDM You can perform such operations using block expression.

```c++
P("r,s") = C("r,i").block({0,0}, {nocc + nvirt, nocc}) * C("s,i").block({0,0}, {nocc + nvirt, nocc});
```

You can see examples of more block expressions in the unit test here:
https://github.com/ValeevGroup/tiledarray/blob/master/tests/expressions.cpp#L164

As for Eigenvalue solver, there are no plans to add this feature. I understand that this is the standard method for solving many QC problems. Unfortunately, this is problematic in distributed memory environments for a number of reasons, which I will not go into at this time. For this reason, our group has implemented other solutions that avoid the need for an Eigenvalue solver. If you are interested in more details about our approach or are interested in collaborations please contact @evaleev directly.

If you absolutely need an Eigenvalue solver, the solution that we have used (for testing and verifications purposes) has been to use http://libelemental.org.
