### ISSUE TITLE
Intel 19 compiling/testing

### ISSUE THREAD

**Issue by ambmax00** [ValeevGroup/tiledarray#164]
Hi,
I had no trouble running TA with gcc, but it's different with intel compilers.
During compilation, the compiler fails to deduce the type for auto variables like
static constexpr auto is_lazy_tile_v = is_lazy_tile_tile<std::decay_t<T>>::value;
in tile_op/unary_wrapper.h and tile_op/binary_wrapper.h

Substituting auto by bool for all of them solves the problem and makes it compile just fine. Later in the tests, I get the following problem:

/export/home/mambrois/TA/TAintel/tests/type_traits.cpp(257): error: in "type_traits_suite/convertibility": check lazy_tile_has_conversion_operator_to_tile has failed
/export/home/mambrois/TA/TAintel/tests/expressions_impl.h(581): fatal error: in "expressions_sparse_suite/assign_subblock_block<ExpressionsFixture<TiledArray__Tensor<int, Eigen__aligned_allocator<int> >, TiledArray__SparsePolicy>>": unexpected exception thrown by c("a,b,c").block({3, 3, 3}, {5, 5, 5}) = 2 * a("a,b,c").block({3, 3, 3}, {5, 5, 5})
/export/home/mambrois/TA/TAintel/tests/expressions_impl.h(659): fatal error: in "expressions_sparse_suite/assgin_subblock_permute_block<ExpressionsFixture<TiledArray__Tensor<int, Eigen__aligned_allocator<int> >, TiledArray__SparsePolicy>>": unexpected exception thrown by c("a,b,c").block({3, 3, 3}, {5, 5, 5}) = a("c,b,a").block({3, 3, 3}, {5, 5, 5})
/export/home/mambrois/TA/TAintel/tests/expressions_impl.h(758): fatal error: in "expressions_sparse_suite/assign_subblock_block_contract<ExpressionsFixture<TiledArray__Tensor<int, Eigen__aligned_allocator<int> >, TiledArray__SparsePolicy>>": unexpected exception thrown by w("a,b").block({3, 3}, {5, 5}) = a("a,c,d").block({3, 2, 3}, {5, 5, 5}) * b("c,d,b").block({2, 3, 3}, {5, 5, 5})
/export/home/mambrois/TA/TAintel/tests/expressions_impl.h(769): fatal error: in "expressions_sparse_suite/assign_subblock_block_permute_contract<ExpressionsFixture<TiledArray__Tensor<int, Eigen__aligned_allocator<int> >, TiledArray__SparsePolicy>>": unexpected exception thrown by w("a,b").block({3, 3}, {5, 5}) = a("a,c,d").block({3, 2, 3}, {5, 5, 5}) * b("d,c,b").block({3, 2, 3}, {5, 5, 5})

*** 5 failures are detected in the test module "Master Test Suite"

My previous modification is probably the cause of this, but I'm not sure how to solve this.

**Comment by evaleev** [comment]
was fixed via ac27dce1e4b6e8b3f5b8ddba4f36f67d2494c99b ... please try.

would appreciate a PR with your changes for intel19!
