### ISSUE TITLE
CMake newer than 3.9 fails building TiledArray on ALCF Theta

### ISSUE THREAD

**Issue by victor-anisimov** [ValeevGroup/tiledarray#188]
-- The CXX compiler identification is GNU 8.3.0
-- Cray Programming Environment 2.6.1 CXX
-- Check for working CXX compiler: /opt/cray/pe/craype/2.6.1/bin/CC
-- Check for working CXX compiler: /opt/cray/pe/craype/2.6.1/bin/CC - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.12.3") 
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- The C compiler identification is GNU 8.3.0
-- Cray Programming Environment 2.6.1 C
-- Check for working C compiler: /opt/cray/pe/craype/2.6.1/bin/cc
-- Check for working C compiler: /opt/cray/pe/craype/2.6.1/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES) (found version "3.1")
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES) (found version "3.1")
CMake Error at /home/anisimov/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) (found version
  "3.1")

      Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  

Call Stack (most recent call first):
  /home/anisimov/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /home/anisimov/cmake/share/cmake-3.17/Modules/FindMPI.cmake:1717 (find_package_handle_standard_args)
  external/madness.cmake:151 (find_package)
  CMakeLists.txt:257 (include)

-- Configuring incomplete, errors occurred!
See also "/home/anisimov/mpqc4/tiledarray/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/ValeevGroup/tiledarray/files/4411462/CMakeOutput.log)

This is the result of using the latest CMake 3.17. Theta has cmake/3.9.1  cmake/3.11.4 cmake/3.14.5. None of those work except cmake/3.9.1. I had to modify the version test in CMakeLists.txt from 3.10 to 3.9:

cmake_minimum_required (VERSION 3.9.0)

How to reproduce:

module swap PrgEnv-intel PrgEnv-gnu
module unload perftools-base atp darshan xalt cray-libsci
module load cmake/3.14.5
module load boost/gnu/1.64.0

export ROOT=$HOME/mpqc4
export CC=cc
export CXX=CC
export INTEL_DIR=/theta-archive/intel/compilers_and_libraries_2019.5.281/linux
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/lib/pkgconfig

export CRAYPE_LINK_TYPE=dynamic

rm -rf $ROOT/install

# Eigen3
cd $ROOT
cd eigen-3.3.7
rm -rf build; mkdir build; cd build
cmake -D CMAKE_INSTALL_PREFIX=$ROOT/install -DCMAKE_CXX_COMPILER=CC ..
make install

# GMP
cd $ROOT
cd gmp-6.1.2
rm -rf build; mkdir build; cd build
../configure --prefix=$ROOT/install --enable-cxx CC=cc CXX=CC
make -j 20
make install

# Libint 2.7.0
cd $ROOT
cd libint-2.7.0-beta.2
rm -rf build; mkdir build; cd build
cmake -D CMAKE_INSTALL_PREFIX=$ROOT/install -D CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH};${ROOT}/install" -DCMAKE_CXX_COMPILER=CC ..
make -j 20
make install

# TiledArray
cd $ROOT
rm -rf tiledarray
git clone https://github.com/ValeevGroup/tiledarray.git tiledarray
cp CMakeLists.txt.tiledarray tiledarray/CMakeLists.txt
cd tiledarray; rm -rf build; mkdir build; cd build
cmake -D CMAKE_INSTALL_PREFIX=$ROOT/install \
      -D CMAKE_TOOLCHAIN_FILE=$ROOT/theta-gcc-mpi-mkl-tbb.cmake \
      -D ENABLE_CUDA=OFF \
      -D ENABLE_TBB=ON \
      -D BUILD_SHARED_LIBS=OFF \
      -D CMAKE_PREFIX_PATH="${ROOT}/install;${CMAKE_PREFIX_PATH}" \
      CXX=CC ..

the difference between theta-gcc-mpi-mkl-tbb.cmake and tiledarray/cmake/toolchains/gcc-mpi-mkl-tbb.cmake

set(CMAKE_C_COMPILER cc)
set(CMAKE_CXX_COMPILER CC)
set(MPI_C_COMPILER cc)
set(MPI_CXX_COMPILER CC)

if ($ENV{GCC_VERSION})
  set(CMAKE_C_COMPILER gcc-$ENV{GCC_VERSION})
  set(CMAKE_CXX_COMPILER g++-$ENV{GCC_VERSION})
else ()
  set(CMAKE_C_COMPILER gcc)
  set(CMAKE_CXX_COMPILER g++)
endif ()
set(MPI_C_COMPILER mpicc)
set(MPI_CXX_COMPILER mpicxx)

Currently Loaded Modulefiles:
modules/3.2.11.3                                      
gcc/8.3.0                                             
craype-mic-knl                                        
craype-network-aries                           
craype/2.6.1                                          
cray-mpich/7.7.10                                     
nompirun/nompirun                                     
trackdeps                                             
udreg/2.3.2-6.0.7.1_5.15__g5196236.ari    
ugni/6.0.14.0-6.0.7.1_3.15__gea11d3d.ari 
pmi/5.0.14
dmapp/7.1.1-6.0.7.1_6.6__g45d1b37.ari
gni-headers/5.0.12.0-6.0.7.1_3.13__g3b1768f.ari
xpmem/2.2.15-6.0.7.1_5.13__g7549d06.ari
job/2.2.3-6.0.7.1_5.48__g6c4e934.ari
dvs/2.7_2.2.120-6.0.7.1_12.5__g74cb2cc4
alps/6.6.43-6.0.7.1_5.51__ga796da32.ari
rca/2.2.18-6.0.7.1_5.52__g2aa4f39.ari
PrgEnv-gnu/6.0.5
boost/gnu/1.64.0
cmake/3.14.5

**Comment by victor-anisimov** [comment]
OK. Got the issue resolved.

I tracked the problem that TiledArray has with all newer versions of CMake than 3.9 on Cray to toolchains supplied with TiledArray. The usual form  
set(CMAKE_C_COMPILER cc)
set(CMAKE_CXX_COMPILER CC)
set(MPI_C_COMPILER cc)
set(MPI_CXX_COMPILER CC)
works with CMake ver. 3.9.1 on Cray but does not work with any newer version of CMake.

Apparently, CMake changed something in their FindMPI.cmake so that it now requires full path to the MPI compilers:
set(CMAKE_C_COMPILER cc)
set(CMAKE_CXX_COMPILER CC)
set(MPI_C_COMPILER /opt/cray/pe/craype/2.6.1/bin/cc)
set(MPI_CXX_COMPILER /opt/cray/pe/craype/2.6.1/bin/CC)

Shipping TiledArray with Cray version of gcc-mpi-mkl-tbb.cmake that includes the described change would save a ton of time for Cray users of TiledArray.

**Comment by evaleev** [comment]
@victor-anisimov
