### ISSUE TITLE
CBLAS Detection

### ISSUE THREAD

**Issue by ryanmrichard** [ValeevGroup/tiledarray#190]
I just pulled master and it broke my build (toolchain at bottom), specifically I get the error:

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ryan/CLionProjects/tiledarray/cmake-build-debug/external/madness-build
-- ** Done configuring MADNESS
-- custom target build-madness is expected to build these byproducts: /home/ryan/CLionProjects/tiledarray/cmake-build-debug/external/madness-build/src/madness/world/libMADworld-static.a
-- MKL library not found
CMake Error at cmake-build-debug/_deps/btas-src/cmake/modules/FindCBLAS.cmake:100 (MESSAGE):
  CBLAS library not found.  Please specify library location
Call Stack (most recent call first):
  cmake-build-debug/_deps/btas-src/CMakeLists.txt:122 (find_package)
```

I don't know if this is a problem with TA forwarding variables to BTAS, or a problem with BTAS's detection, but either way I tried providing the path to the header using:

- `LAPACK_INCLUDE_DIRS` (as shown in toolchain file)
- `CMAKE_PREFIX_PATH` (leaving off the `include`)
- `CBLAS_INCLUDE_DIR` (same form as `LAPACK_INCLUDE_DIRS`)
-`CBLAS_DIR` (leaving off the include)

(and yes I verified cblas.h resides there). I didn't rule out that CBLAS detection is failing because of not being able to find the library, but I would have expected the `CMAKE_PREFIX_PATH`/`CBLAS_DIR` options to work in those cases (`LAPACK_LIBRARIES`'s value is set for MADNESS already so I can't change that).

This is my CMake toolchain:

```
set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CPP_COMPILER /usr/bin/g++)
set(MPI_C_COMPILER "/home/ryan/spack/opt/spack/linux-ubuntu19.10-x86_64/gcc-9.2.1/mpich-3.3-fdbhlvvanqhu2ctj2smk6uhgqyr2tzvg/bin/mpicc")
set(MPI_CXX_COMPILER "/home/ryan/spack/opt/spack/linux-ubuntu19.10-x86_64/gcc-9.2.1/mpich-3.3-fdbhlvvanqhu2ctj2smk6uhgqyr2tzvg/bin/mpicxx")
set(LAPACK_LIBRARIES "-L/home/ryan/spack/opt/spack/linux-ubuntu19.10-x86_64/gcc-9.2.1/openblas-0.3.6-tkkexh3snvboupwxs2ksrkykcy3zoqmt/lib -lopenblas")
set(LAPACK_INCLUDE_DIRS "/home/ryan/spack/opt/spack/linux-ubuntu19.10-x86_64/gcc-9.2.1/openblas-0.3.6-tkkexh3snvboupwxs2ksrkykcy3zoqmt/include")
```

**Comment by evaleev** [comment]
btas does not support looking for cblas in openblas ... It does not know anything about LAPACK_LIBRARIES either. See BTAS' FindCBLAS for details.

**Comment by ryanmrichard** [comment]
How do I help BTAS find CBLAS? 

I went ahead and installed MKL. It's located at `${HOME}/intel/mkl`. Setting the usual variables, `CMAKE_PREFIX_PATH`, `CBLAS_DIR`, and `MKL_DIR` to this value does nothing.

**Comment by kmp5VT** [comment]
There is a known issue with linking TIledArray's MKL directory with BTAS that should be fixed soon.  
To provide TiledArray with a custom intel path you can set the environment variable `INTEL_DIR="${HOME}/intel/mkl"`
It might be a better idea to write an executable which can generate all necessary intel variables such as `intel.sh`:
```
export INTEL_DIR=/path/to/intel

# "load" TBB
source ${INTEL_DIR}/tbb/bin/tbbvars.sh intel64
export TBB_DIR=${TBBROOT}
export TBB_INC=${TBB_DIR}/include
export TBB_LIB=${TBB_DIR}/lib/intel64/gcc4.7

# "load" MKL
source ${INTEL_DIR}/mkl/bin/mklvars.sh intel64
export MKL_DIR=${MKLROOT}
export MKL_INC=${MKLROOT}/include
export MKL_LIB=${MKLROOT}/lib/intel64

# "load" Intel MPI
source ${INTEL_DIR}/mpi/intel64/bin/mpivars.sh intel64
export IMPI_DIR=${I_MPI_ROOT}
export IMPI_BIN=${IMPI_DIR}/intel64/bin
export IMPI_INC=${I_MPI_ROOT}/intel64/include
export IMPI_LIB=${I_MPI_ROOT}/intel64/lib
export VT_MPI_BIN=${IMPI_BIN}
export VT_MPI_INC=${IMPI_INC}
export VT_MPI_LIB=${IMPI_LIB}
export VT_MPI_ROOT=${I_MPI_ROOT}
```

**Comment by evaleev** [comment]
will be fixed (fingers crossed) in https://github.com/BTAS/BTAS/pull/104 ... upgraded FindMKL to pytorch's (which was based on the same source as the original BTAS FindMKL module).

To find MKL you in general need to source mklvars.sh unless your intel stack is in /opt/intel . FindMKL is not standard and does not look in MKL_DIR or anything like this.
