### ISSUE TITLE
MPQC complain about TiledArray for ambiguous call

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#22]
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates_util.cc:36:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates.h:36:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/tiledarray.h:24:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/array.h:25:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/tensor.h:23:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/range.h:24:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/size_array.h:23:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/outer.h:29:
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:409:9: error: call to 'for_each_block_ptr' is ambiguous
        **for_each_block_ptr(op, result + i, Block<Args>(args + i)...);**
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:497:7: note: in instantiation of function template specialization
      'TiledArray::math::vector_ptr_op<(lambda at /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:496:17) &,
      TiledArray::Tensor<double, Eigen::aligned_allocator<double> >>' requested here
      vector_ptr_op(op, n, arg);

**Comment by justusc** [comment]
Can you please post the entire error message?

**Comment by pchong90** [comment]
It looks a little bit messy.

In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates_util.cc:36:
In file included from /Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates.h:36:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/tiledarray.h:24:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/array.h:25:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/tensor.h:23:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/range.h:24:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/size_array.h:23:
In file included from /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/outer.h:29:
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:409:9: error: call to 'for_each_block_ptr' is ambiguous
        for_each_block_ptr(op, result + i, Block<Args>(args + i)...);
        ^~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:497:7: note: in instantiation of function template specialization
      'TiledArray::math::vector_ptr_op<(lambda at /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:496:17) &,
      TiledArray::Tensor<double, Eigen::aligned_allocator<double> >>' requested here
      vector_ptr_op(op, n, arg);
      ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/tensor.h:86:15: note: in instantiation of function template specialization
      'TiledArray::math::destroy_vector<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > >' requested here
        math::destroy_vector(range_.volume(), data_);
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2431:13: note: in instantiation of member function
      'TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Impl::~Impl' requested here
            delete __ptr;
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2630:13: note: in instantiation of member function
      'std::__1::default_delete<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Impl>::operator()' requested here
            __ptr_.second()(__tmp);
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2598:46: note: in instantiation of member function
      'std::__1::unique_ptr<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Impl, std::__1::default_delete<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >,
      Eigen::aligned_allocator<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > > >::Impl> >::reset' requested here
    _LIBCPP_INLINE_VISIBILITY ~unique_ptr() {reset();}
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4031:21: note: in instantiation of member function
      'std::__1::unique_ptr<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Impl, std::__1::default_delete<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >,
      Eigen::aligned_allocator<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > > >::Impl> >::~unique_ptr' requested here
    unique_ptr<_Yp> __hold(__p);
                    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/tensor.h:182:7: note: in instantiation of function template specialization
      'std::__1::shared_ptr<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Impl>::shared_ptr<TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >,
      Eigen::aligned_allocator<TiledArray::Tensor<double, Eigen::aligned_allocator<double> > > >::Impl>' requested here
      pimpl_(new Impl(range))
      ^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates_util.cc:69:15: note: in instantiation of member function
      'TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Tensor' requested here
    eval_type tile(owner_->trange().make_tile_range(index_), eval_type::value_type(i3i4_range));
              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:223:5: note: candidate function [with Op = (lambda at
      /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:496:17) &, Result = TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> >, Args = <>]
    for_each_block_ptr(Op&& op, Result* const result,
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:232:5: note: candidate function [with Op = (lambda at
      /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:496:17) &, Result = TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> >, Args = <>]
    for_each_block_ptr(Op&& op, Result* const result, Block<Args>&&... args) {
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:409:9: error: call to 'for_each_block_ptr' is ambiguous
        for_each_block_ptr(op, result + i, Block<Args>(args + i)...);
        ^~~~~~~~~~~~~~~~~~
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:482:7: note: in instantiation of function template specialization
      'TiledArray::math::vector_ptr_op<(lambda at /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:481:17) &,
      TiledArray::Tensor<double, Eigen::aligned_allocator<double> >>' requested here
      vector_ptr_op(op, n, result);
      ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/tensor.h:184:13: note: in instantiation of function template specialization
      'TiledArray::math::uninitialized_fill_vector<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > >' requested here
      math::uninitialized_fill_vector(range.volume(), value, pimpl_->data_);
            ^
/Users/ChongPeng/Workspace/Development/source/mpqc/src/lib/chemistry/qc/mbptr12/sr_r12intermediates_util.cc:69:15: note: in instantiation of member function
      'TiledArray::Tensor<TiledArray::Tensor<double, Eigen::aligned_allocator<double> >, Eigen::aligned_allocator<TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> > > >::Tensor' requested here
    eval_type tile(owner_->trange().make_tile_range(index_), eval_type::value_type(i3i4_range));
              ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:223:5: note: candidate function [with Op = (lambda at
      /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:481:17) &, Result = TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> >, Args = <>]
    for_each_block_ptr(Op&& op, Result* const result,
    ^
/Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:232:5: note: candidate function [with Op = (lambda at
      /Users/ChongPeng/Workspace/Development/install/tiledarray-clang/include/TiledArray/math/vector_op.h:481:17) &, Result = TiledArray::Tensor<double,
      Eigen::aligned_allocator<double> >, Args = <>]
    for_each_block_ptr(Op&& op, Result* const result, Block<Args>&&... args) {
    ^
3 warnings and 2 errors generated.
make[2]: *** [src/lib/chemistry/qc/mbptr12/CMakeFiles/mbptr12.dir/sr_r12intermediates_util.cc.o] Error 1
make[1]: *** [src/lib/chemistry/qc/mbptr12/CMakeFiles/mbptr12.dir/all] Error 2
make: *** [all] Error 2

**Comment by justusc** [comment]
@pchong90 Yes but you truncated all the valuable diagnostic information that is necessary to resolve the error.
