### ISSUE TITLE
Eigen is no longer hosted on Bitbucket but on Gitlab.

### ISSUE THREAD

**Issue by hjjvandam** [ValeevGroup/tiledarray#220]
When building TiledArrays eigen.cmake will try and download the Eigen source code from bitbucket (http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2). However, it seems that the code no longer lives in that location. Instead it now seems to live at https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2 (see: http://eigen.tuxfamily.org/index.php?title=Main_Page for details). Maybe this needs updating.

**Comment by evaleev** [comment]
this is fixed via a3db293038ba1c0ac3f39bc4b91b68f89e970a61 and some subsequent additional fixes. will be merged into master via #218 , I recommend you use that until the merge
