### ISSUE TITLE
CMakeLists.txt expects a git repository checkout even for releases

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/tiledarray#25]
Running cmake on one of the release tarballs results in:

```
-- Found Git: /usr/bin/git (found version "2.1.4") 
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at CMakeLists.txt:103 (string):
  string sub-command REGEX, mode MATCH regex "[0-9a-f]*" matched an empty
  string.
[...]
-- Configuring incomplete, errors occurred!
```

It seems CMakeLists.txt unconditionally expects a git repository, if I comment out lines 98-104 in CMakeLists.txt, cmake configures fine.

**Comment by justusc** [comment]
Git is used to download some dependencies that are not found during configure. I think the better course of action here is to check for git when it is needed, i.e. when a dependency is not found. I will try to have a fix early next week.

FYI, a new release is in the works, and should be available soon (August time frame). We are in the process of doing robustness tests.

**Comment by justusc** [comment]
The correct solution is to add the flag to the LDFLAGS inside the .am files. This means I will need to modify the code to test it. I will make the changes to my fork tomorrow so you can test it.
