### ISSUE TITLE
270b5240 should be cherry-picked to 0.4-alpha branch 

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/tiledarray#29]
I think the title says it all, in the 0.4-alpha branch, src/TiledArray/algebra/diis.h includes "`<TiledArray/eigen.h>`", which no longer exists. 270b5240 fixes this on master and I think this should be cherry-picked to 0.4-alpha.

**Comment by justusc** [comment]
Closed via 6878e958ebf5864c0f7373a53c1c266d0faf4987.
