### ISSUE TITLE
Possible Performance Issue with DirectTile Array Contraction?

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#32]
I noticed some inconsistency in the performance in direct tile array contraction. 
Here is the output. 
```
CC Test
Frozen Core: 16 electrons
Block Size in MO     16
TiledRange1 Occupied ( tiles = [ 0, 2 ), elements = [ 0, 21 ) )
TiledRange1 Virtual  ( tiles = [ 0, 51 ), elements = [ 0, 803 ) )

Begining CC
start iteration
iter     deltaE                residual             energy         U/second   total/second
1  0.0611231317123433  4.26012753086288e-10  -1.53904486737057  7009.242363154 7408.379613357
2  0.0399401658471812  1.73605236907515e-10  -1.57898503321775  5475.195483026 5702.249691427
3  0.0107532244924691  7.03545478472614e-11  -1.58973825771022  8330.972643913 8562.005677823
4  0.000622645030980973  2.26645163814899e-11  -1.58911561267924  4515.994389942 4761.335676287
5  0.000292624947780151  1.0037030826343e-11  -1.58882298773146  4015.300883278 4247.982380656
6  0.00030492243288549  3.97572330838135e-12  -1.58912791016435  2969.095039533 3162.468504955
7  0.000231114981430247  1.63338874450642e-12  -1.58889679518291  1563.37255113 1754.09951477
8  4.19793105643773e-05  6.21390025858168e-13  -1.58893877449348  3897.680281818 4118.719245746
9  9.66978594729717e-06  3.44425382366613e-13  -1.58892910470753  11974.894220928 12752.963265018
10  5.62034317974636e-07  1.63034768374226e-13  -1.58892854267321  4978.137758322 5214.837211002
```
The U part is the contraction between direct integral array with another array and it scales O(N^6).
```
(t2("a,b,i,j")*Ca_("q,a"))*Ca_("s,b") + tc("i,q") * tc("j,s")) * direct_ao_("p,q,r,s")
```
 total - U is everything else. 
I notice that total - U is around 200-400 seconds per iteration. While the U time range from 1500 to 12000 seconds. 

I was wondering what causes this problem. It could be the integral generation in direct tile or something in TA.

**Comment by pchong90** [comment]
This is QZ basis calculation. So the block size in `direct_ao_` is very large. That could also be the issue.

**Comment by justusc** [comment]
One thing to keep in mind when timing TA expressions, is that you need to use fences to obtain accurate timing information. The reason for this is that some of the tasks in the expression evaluation may not have finished with the expression assignment operator exits. You must place a fence before each call to timer, otherwise you can get an overlap in work from previous expressions or subsequent expressions.

The best way to account for the time in your code is to add timers to different pieces of code. For example, you can add a timer to the lazy tile type conversion operator.

**Comment by justusc** [comment]
This could have something to do with the way MADNESS distributes tasks between threads, i.e. MADNESS will allocate up to 128 tasks per thread. It may be that the distribution between threads is better in some iterations than in others.

One way to test this (if it is in fact a load balance issue) is to use TBB, which has thread level task stealing.
