### ISSUE TITLE
Need to update CMake hashes

### ISSUE THREAD

**Issue by ryanmrichard** [ValeevGroup/tiledarray#332]
This stems from NWChemEx-Project/TensorWrapper#62. I think this https://github.com/ValeevGroup/kit-cmake/commit/f946aa274745da09702a727492f1cabb843dc9e6 commit broke TA. I'm guessing a hash needs updated somewhere. I'm going to see if I can track down which hash.

**Comment by evaleev** [comment]
fixed via #331
