### ISSUE TITLE
delta function

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#39]
In multireference theories, there are lots of instances where one has to do:

```
a("i,j,k,l") += delta("i,j") * b("k,l")
```

where delta is the Kronecker delta. This has to be implemented in some way (there are higher order analogues too - imagine calculating hole 4RDM from particle RDMs).

**Comment by justusc** [comment]
This could be handled with a custom tile. It would require you to define the arithmetic operations between a delta tile and a TA::Tensor. There are quite a few of them, but they are all relatively simple to implement.

This is probably not something we want to include in TA, though @evaleev may have a different opinion.

**Comment by shiozaki** [comment]
At least you guys could provide an example. This is beyond what I can do (with my time somewhat limited).

**Comment by justusc** [comment]
Another option for this is to use an identity matrix. I believe it would generate the same result.

I will see what I can do about an example.

**Comment by shiozaki** [comment]
Also wanted to note that there could be a few delta's in a single expression. d below is a delta whereas. For instance the first line is 2RDM with two delta's multiplied, which is to be slotted in to 4RDM storage. There are hundreds of these expressions.
```
Gamma165(x0, x1, x3, x4, x5, x2, x6, x7)
 -1.0 <0|[x3+(2)x4(2)x0+(3)x7(3) d(x2x6) d(x1x5)]|0>*
  2.0 <0|[x3+(2)x4(2)x0+(3)x7(3) d(x2x5) d(x1x6)]|0>*
  2.0 <0|[x0+(3)x7(3) d(x2x5) d(x1x3) d(x4x6)]|0>*
  2.0 <0|[x0+(2)x4(2)x6+(3)x7(3) d(x2x5) d(x1x3)]|0>*
 -1.0 <0|[x0+(3)x7(3) d(x4x5) d(x2x6) d(x1x3)]|0>*
 -1.0 <0|[x0+(2)x4(2)x5+(3)x7(3) d(x2x6) d(x1x3)]|0>*
 -1.0 <0|[x0+(1)x2(1)x6+(3)x7(3) d(x4x5) d(x1x3)]|0>*
 -1.0 <0|[x5+(1)x2(1)x0+(3)x7(3) d(x4x6) d(x1x3)]|0>*
 -1.0 <0|[x0+(2)x4(2)x5+(1)x2(1)x6+(3)x7(3) d(x1x3)]|0>*
 -1.0 <0|[x0+(3)x7(3) d(x4x6) d(x2x3) d(x1x5)]|0>*
 -1.0 <0|[x0+(2)x4(2)x6+(3)x7(3) d(x2x3) d(x1x5)]|0>*
 -1.0 <0|[x0+(1)x2(1)x3+(3)x7(3) d(x4x6) d(x1x5)]|0>*
 -1.0 <0|[x0+(1)x2(1)x3+(2)x4(2)x6+(3)x7(3) d(x1x5)]|0>*
  2.0 <0|[x0+(3)x7(3) d(x4x5) d(x2x3) d(x1x6)]|0>*
 -1.0 <0|[x5+(2)x4(2)x0+(3)x7(3) d(x2x3) d(x1x6)]|0>*
 -1.0 <0|[x3+(1)x2(1)x0+(3)x7(3) d(x4x5) d(x1x6)]|0>*
 -1.0 <0|[x3+(2)x4(2)x5+(1)x2(1)x0+(3)x7(3) d(x1x6)]|0>*
  2.0 <0|[x0+(0)x1(0)x6+(3)x7(3) d(x4x5) d(x2x3)]|0>*
 -1.0 <0|[x0+(0)x1(0)x5+(3)x7(3) d(x4x6) d(x2x3)]|0>*
 -1.0 <0|[x0+(0)x1(0)x5+(2)x4(2)x6+(3)x7(3) d(x2x3)]|0>*
  2.0 <0|[x0+(0)x1(0)x3+(3)x7(3) d(x4x6) d(x2x5)]|0>*
  2.0 <0|[x0+(0)x1(0)x3+(2)x4(2)x6+(3)x7(3) d(x2x5)]|0>*
 -1.0 <0|[x0+(0)x1(0)x3+(3)x7(3) d(x4x5) d(x2x6)]|0>*
 -1.0 <0|[x0+(0)x1(0)x3+(2)x4(2)x5+(3)x7(3) d(x2x6)]|0>*
 -1.0 <0|[x0+(0)x1(0)x3+(1)x2(1)x6+(3)x7(3) d(x4x5)]|0>*
 -1.0 <0|[x0+(0)x1(0)x5+(1)x2(1)x3+(3)x7(3) d(x4x6)]|0>*
 -1.0 <0|[x0+(0)x1(0)x3+(2)x4(2)x5+(1)x2(1)x6+(3)x7(3)]|0>*
```

**Comment by evaleev** [comment]
Proper implementation will require:
  1. custom KroneckerDelta tensor class (generalized to allow products of regular 2-index deltas),
  2. support for expressions involving Array's with different tile types, and
  3. custom optimized implementation of operations involving KroneckerDelta and TA::Tensor (or the desired user "dense" tensor type).

Will create separate issue for 2, the rest belongs here.

**Comment by justusc** [comment]
I am working on building support for different tile types. It is taking a little longer than I initially planned since the work also includes changes needed for complex conjugate support.

**Comment by shiozaki** [comment]
Any progress?
When it's done, let me know how to do
```
a("i,j,k,l") = delta("i,j") * b("k,l")
```
and also how to do this tile-wise (i.e., loop over tiles of a and do something inside it - essentially, how to use this as a lazy tile).

**Comment by justusc** [comment]
Still working on the necessary changes.

**Comment by evaleev** [comment]
added [prerequisite milestone: mixing tile types in expressions](https://github.com/ValeevGroup/tiledarray/milestones/4)

**Comment by ryanmrichard** [comment]
I take it this still isn't implemented? If not I can take a stab at it as I need an identity matrix for PAOs.

**Comment by evaleev** [comment]
@ryanmrichard you don't need this

**Comment by evaleev** [comment]
for the record: this is partially addressed ... see https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/special/kronecker_delta.h and https://github.com/ValeevGroup/tiledarray/blob/master/tests/expressions_mixed.cpp ... @ryanmrichard to get non-lazy diagonal tensors see https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/special/diagonal_array.h , you don't need lazy diagonal tiles.
