### ISSUE TITLE
Block expression - move assignment broken

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#40]
See line 227 of blk_tsr_expr.h.
```
// works
//c("m,n").block({1,1},{2,2}) = a("m,k").block({0,1},{1,2}) * b("k,n").block({1,0}, {2,1});
// fails
  c("m,n").block({1,1},{2,2}) = a("n,m").block({0,1},{1,2});
// works
//c("m,n").block({1,1},{2,2}) += a("n,m").block({0,1},{1,2});
// works
//auto tmp = a("n,m").block({0,1},{1,2});
//c("m,n").block({1,1},{2,2}) = tmp;
```

**Comment by shiozaki** [comment]
Actually I don't know what to expect. Obviously my generated code meant to copy the block, but obviously it's calling move-assigment.

**Comment by justusc** [comment]
This looks like a compiler bug to me. `BlkTsrExpr` has a copy assignment operator that should be used since the move assignment operator has been explicitly deleted. I added a move assignment operator that does the same thing as the copy constructor as a workaround.

**Comment by shiozaki** [comment]
Believe the behavior of gcc 5.2 is legitimate in that deleted functions participate in overload resolutions (at least that was what it was in N2346). In any case I guess your fix should have solved this.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2346.htm#delete
> The definition form =delete; indicates that the function may not be used. However, all lookup and overload resolution occurs before the deleted definition is noted. That is, it is the definition that is deleted, not the symbol; overloads that resolve to that definition are ill-formed.

**Comment by justusc** [comment]
I am fairly certain it is not correct. This is the key statement:

> However, all lookup and overload resolution occurs before the deleted definition is noted.

In other words, it should have picked up the copy assignment operator that is present before failing because the move assignment operator was deleted.

**Comment by evaleev** [comment]
Deleted functions do participate in overload resolution

http://stackoverflow.com/questions/14085620/why-do-c11-deleted-functions-participate-in-overload-resolution
Justus, you are reading it backwards. "before deleted definition is noted"
means "before delete statement is taken into account, i.e. acting as if the
operator/function is not deleted".
