### ISSUE TITLE
does assignment operation on expression do deep copy?

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#47]
```
t2("a,b,i,j") = g_abij("a,b,i,j");
```
After I update t2, g_abij is also updated. So, it this a bug? Or, is there another way to do deep copy?

**Comment by justusc** [comment]
The expression you gave should perform a deep copy.

**Comment by justusc** [comment]
... For the tile data.

**Comment by pchong90** [comment]
what do you mean by for the tile data? Does it deep copy all the elements stored in the tile?
let say some toy code
```
g = {{1,2},{3,4}};
t("i,j") = g("i,j");
t("i,j") += 1;
std::cout <<  t;
std::cout << g;
```
in here, `t` will be `{{2,3,},{4,5}}`. In TiledArray, `g` will also be `{{2,3},{4,5}}` ?

**Comment by justusc** [comment]
No, g will not be the same as t in your example.

What I mean is that tiles will be cloned in your first example, but some array metadata will be copied or shallow copied.

**Comment by pchong90** [comment]
OK, let me show you my code
```
t2("a,b,i,j") = g_abij("a,b,i,j");
TA::foreach_inplace(t2,operation);
```
after doing this, I print `t2` and `g_abij`, and they have exactly the same elements. (the elements are updated, not the same as original `g_abij`)

**Comment by justusc** [comment]
This looks like a bug then. It is not something I will have time to look at until I return from my trip.

You may not want to use `foreach_inplace` if you want a deep copy anyway.

**Comment by pchong90** [comment]
OK, I got it now. I will switch to use `foreach` now. Thank you!

**Comment by justusc** [comment]
I am going to relabel this as a feature, not a bug.
