### ISSUE TITLE
Refactoring error?

### ISSUE THREAD

**Issue by ryanmrichard** [ValeevGroup/tiledarray#52]
I think you missed this while refactoring:
https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/array_impl.h#L283

specifically:
```
other.tensor_ 
```
should be:
```
 other.array_
```

**Comment by justusc** [comment]
Thanks for the bug report.

Fixed via a67cfb82e3920b846d345812880ed7a90f117b8e.
