### ISSUE TITLE
bug (contraction)

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#60]
The following dies at contraction without error messages. The memory usage is 5%. They are large matrices, but lapack can multiply them (with the integer 4 interface); so I think this should be a bug.

```cpp
#include <tiledarray.h> // for TiledArray library
#include <complex>

namespace TA = TiledArray;
using namespace std;

int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  vector<size_t> aa{0,5,10};

  // Construct a set of TiledRange1's
  TiledArray::TiledRange1 tileaa(aa.begin(), aa.end());

  vector<TiledArray::TiledRange1> ranges1{tileaa, tileaa, tileaa, tileaa, tileaa, tileaa, tileaa, tileaa};
  TA::TiledRange trange1(ranges1.begin(), ranges1.end());
  vector<TiledArray::TiledRange1> ranges2{tileaa, tileaa, tileaa, tileaa, tileaa};
  TA::TiledRange trange2(ranges2.begin(), ranges2.end());

  // Construct array objects.
  TA::Array<complex<double>,8> A(world, trange1);
  TA::Array<complex<double>,5> B(world, trange2);
  TA::Array<complex<double>,5> C(world, trange2);
  A.fill_local(0.0);
  B.fill_local(1.0);
  C.fill_local(2.0);

  cout << "starting multiplication" << endl;
  A("o1,o2,o3,o4,o5,o6,o7,o8") += B("o0,o1,o2,o3,o4") * C("o0,o5,o6,o7,o8");
  // actual code has permutation here, so please do not suggest to merge indices!
  // A("o5,o1,o6,o2,o7,o3,o8,o4") += B("o0,o1,o2,o3,o4") * C("o0,o5,o6,o7,o8");
  cout << "done" << endl;

  world.gop.fence();
  madness::finalize();
  return 0;
}
```

**Comment by shiozaki** [comment]
by the way this appears to work with 1 MPI process...

**Comment by justusc** [comment]
What do you mean by "memory usage is 5%?" Do you mean that there is only 5% memory available.

The memory usage depends on block size. TA trades more memory for faster performance, so it will use more memory than ScaLAPACK, which uses a minimal memory implementation.

One thing to check is that your send and receive buffers are large enough to hold your tiles. I am not sure if Edward mentions this to you. Please see https://github.com/m-a-d-n-e-s-s/madness/wiki/MADNESS-environment-variables for details. You will need to set `MAD_BUFFER_SIZE` environment variable such that it is a little larger than your largest tile (to account for meta data in the message). You can also adjust the number of send and receive buffers if necessary by setting `MAD_SEND_BUFFERS` and `MAD_RECV_BUFFERS` environment variables. This will allow you to control memory usage if the buffers are large. More buffers gives better performance.

**Comment by shiozaki** [comment]
I am saying that memory is abundant. 95% available. The memory is definitely not the issue.

**Comment by justusc** [comment]
OK. The buffer size still could be an issue if your blocks are large. The default size is 1.5 MB.

**Comment by shiozaki** [comment]
You are right - it solved the problem. Thanks much! In retrospect, maybe the error message was wiped out because TiledArray was configured in the Release mode.

Is it possible to set that variable at runtime?

I don't think it reasonable to assume that all of the users of programs that use TA will be able to set MAD variables such as MAD_BUFFER_SIZE  and MAD_NUM_THREADS. I saw in somewhere that the c function  ::set_env is not standard compliant.

**Comment by justusc** [comment]
MADNESS uses `::get_env` so `::set_env` should be available. If we run into trouble, we will probably have to change it at that point. There is also the little problem that the MPI standard does not guarantee environment variables are propagated to all process, only to rank 0. But so far there have been no issues.

Currently there is no way to set the buffers other than via environment variables. You can use `set_env` to modify it, but only before MADNESS is initialized. We have discussed a runtime solution. It would doable, but, again, only before MADNESS is initialized. It may be possible to finalize and reinitialize but I think MPI has issues with this type of behavior.

I know these answers are unsatisfying, but so far it has been a workable solution. Of course may of the improvements in the code have come from user requests/needs. ;-)
