### ISSUE TITLE
bug? (find(ordinal) does not wait)

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#61]
Wrote to you guys an email, but reported here as I have multiple issues now. I thought that the following should work (based on comments etc in the code) - but please close if this is design. In that case I'd appreciate if you could explain why this is supposed to be this way (I thought I've understood the philosophy behind TA but who knows).

```
mpirun -n 10 ./a.out
```
will produce a tensor randomly filled by 2. Adding fence in the middle fix the issue. The error is found only when there are multiple MPI processes.

```cpp
#include <tiledarray.h> // for TiledArray library
#include <complex>

namespace TA = TiledArray;
using namespace std;

int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  vector<size_t> aa{0,2,10};

  // Construct a set of TiledRange1's
  TiledArray::TiledRange1 tileaa(aa.begin(), aa.end());

  vector<TiledArray::TiledRange1> ranges1{tileaa, tileaa, tileaa};
  TA::TiledRange trange1(ranges1.begin(), ranges1.end());

  // Construct array objects.
  TA::Array<complex<double>,3> S(world, trange1);
  S.fill_local(2.0);

  TA::Array<complex<double>,3> A(world, trange1);
  A.fill_local(0.0);
  for (auto it = A.begin(); it != A.end(); ++it) {
    auto range = A.trange().make_tile_range(it.ordinal());
    auto sa = S.trange().tiles().ordinal(S.trange().element_to_tile(range.lobound()));
    assert(sa == it.ordinal());
    A.get_world().taskq.add([](typename TA::Array<complex<double>,3>::value_type i,
                               typename TA::Array<complex<double>,3>::value_type j) { i.add_to(j); },
                            (*it).future(), S.find(sa));
  }

//world.gop.fence();

  TA::Array<complex<double>,3> B(world, trange1);
  B.fill_local(0.0);
  for (auto it = B.begin(); it != B.end(); ++it) {
    auto range = B.trange().make_tile_range(it.ordinal());
    auto sa = A.trange().tiles().ordinal(A.trange().element_to_tile(range.lobound()));
    assert(sa == it.ordinal());
    B.get_world().taskq.add([](typename TA::Array<complex<double>,3>::value_type i,
                               typename TA::Array<complex<double>,3>::value_type j) { i.add_to(j); },
                            (*it).future(), A.find(sa));
  }

  world.gop.fence();
  cout << B << endl;

  world.gop.fence();
  madness::finalize();
  return 0;
}
```

**Comment by justusc** [comment]
I am not sure what error you are seeing, but the code has a race condition without the fence. You are mutating the data of A in a task, then trying to use that data in another task after the fence. These tasks can happen in any order and concurrently.

The intended use of TA is for array tiles to be written once and used multiple times. If array tiles need to be mutated, internally a new array is generated that replaces the old data. We use a lazy cleanup mechanism that keeps the data around until all nodes have destroyed the array, which ensures data is always accessible to remote nodes.

The way I handle this kind of data flow is to reconstruct the array using the meta data from the input array, and shallow copy `Tensor`s (not `Future`s) from one into the other. Take a look at the `inplace_foreach` function for an example of how to mutate tile data safely.
https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/conversions/foreach.h#L141

Try modeling your code after the `inplace_foreach` function. That should solve your problem.

**Comment by shiozaki** [comment]
Thanks - good to know (for some reasons I presumed that dependency is tracked for write and read access). You can just close this.
