### ISSUE TITLE
tiledarray.h pulls in cblas functions definitions

### ISSUE THREAD

**Issue by mbanck** [ValeevGroup/tiledarray#71]
I am having trouble compiling the latest BAGEL (which requires TA for SMITH):

```
make[5]: Entering directory '/«PKGBUILDDIR»/src/util/parallel'
[...]
/bin/bash ../../../libtool  --tag=CXX   --mode=compile mpicxx -DHAVE_CONFIG_H -I. -I../../..   -std=c++11  -I../../.. -g -O2 -DNDEBUG -I/usr/include/eigen3 -std=c++11 -c -o mpi_interface.lo mpi_interface.cc
libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../.. -std=c++11 -I../../.. -g -O2 -DNDEBUG -I/usr/include/eigen3 -std=c++11 -c mpi_interface.cc -o mpi_interface.o
In file included from /usr/include/TiledArray/madness.h:31:0,
                 from /usr/include/tiledarray.h:23,
                 from mpi_interface.cc:38:
/usr/include/madness/tensor/cblas.h:254:65: error: conflicting declaration of C function 'void zdotu_(const integer*, const complex_real8*, const integer*, const complex_real8*, const integer*, complex_real8*)'
             const complex_real8*, const integer*, complex_real8*);
                                                                 ^
In file included from mpi_interface.cc:32:0:
../../../src/util/f77.h:56:7: note: previous declaration 'void zdotu_(std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, const int*)'
  void zdotu_(std::complex<double>*, const int*, const std::complex<double>*, const int*, const std::complex<double>*, const int*);
       ^
make[5]: *** [mpi_interface.lo] Error 1
```

BAGEL just includes ```tiledarray.h```, which pulls in ```TiledArray/madness.h```, which pulls in MADNESS' ```cblas.h```.  I am not quite sure who is to blame here (I might have outdated TA/MADNESS codes), but I wonder whether TA/MADNESS has any business defining BLAS functions like ZDOTU.

**Comment by justusc** [comment]
@mbanck I am not sure either is correct. If you look at the reference CBLAS code, the BLAS function signature is 
```c
#define F77_zdotu_sub zdotusub_
void F77_zdotu_sub( FINT, const void *, FINT, const void *, FINT, void *);
```
and the CBLAS interface function is:
```c
void   cblas_zdotu_sub(const int N, const void *X, const int incX,
                       const void *Y, const int incY, void *dotu);
```
I know CBLAS is for legacy BLAS, and there may be differences in the function signature for newer BLAS (Fortran) compilers. More research is required. Perhaps @shiozaki can give some insight.

**Comment by evaleev** [comment]
TA uses BLAS and certainly has business dealing with cblas.h . We pull MADNESS' cblas.h to reuse the code. The issue you encountered was fixed in https://github.com/m-a-d-n-e-s-s/madness/commit/b244daad24fd3ba20a3e914e7beb1146e010c1b6

**Comment by shiozaki** [comment]
That was madness' bug (amazing nobody had noticed). You could just check the madness version and make sure that the user has Madness that is recent enough.

With the latest TA and Madness, everything works fine for me.

**Comment by shiozaki** [comment]
FYI
https://software.intel.com/en-us/node/528729

**Comment by justusc** [comment]
Thanks for the reference.
