### ISSUE TITLE
add support for indices with negative values

### ISSUE THREAD

**Issue by evaleev** [ValeevGroup/tiledarray#77]

**Comment by justusc** [comment]
Where is this needed? In many places the index space is assumed to be zero based.  The only place I am aware of that needs a negative index is the shift tensor, and only in the internal code.

**Comment by evaleev** [comment]
where (outside Range) are nonnegative indices assumed? (other than via type restriction).

this will be necessary for any kind of standardization.

**Comment by justusc** [comment]
The unsigned integers are used nearly everywhere an index is used. Where templates are used, there are assertions that check that the index values are greater than zero. So basically the entire code base makes this assumption.

I am not sure I see the value of using negative indices, or where it would be used in the public interface. The interface uses templates for most index inputs, which does not preclude the use of signed integer input. Though the integers must be positive.

What kind of standardization are you thinking about? If all that is needed are signed integers, then that should be relatively easy to accommodate. Changing the code to have negative ranges, will be much more involved.

**Comment by evaleev** [comment]
(for posterity, although we already discussed offline)

negative indices are natural to some application domains, that would be the reason.

standardization is the long term goal of projects like Tensor Working Group/BTAS. Unfortunately I saw that C++17 dropped the array support. Ideally a high quality implementation ends up in boost first, then gets standardized.
