### ISSUE TITLE
assertion error triggered at mult.h:134

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#83]
assertion  #failure

```
    template <bool LC, bool RC,
        typename std::enable_if<!LC>::type* = nullptr>
    static result_type eval(const left_type& first, ZeroTensor) {
      TA_ASSERT(false); // Invalid arguments for this operation
      return result_type();
    }
```

I encountered this problem while calling `ConjugateGradientSolver`
line 153 of conjgrad.h 

```
vec_multiply(XX_i, preconditioner);
```

The input matrix `b` is sparse and contains tiles with all 0.

For input to to triggered this error see issue [https://github.com/ValeevGroup/mpqc4/issues/37]

My question: what does this error mean? 
A non-zero tile should be multipliable to zero tile...

**Comment by justusc** [comment]
The function that is asserting is there to satisfy an interface requirement for another part of the code. However, the multiply operation is structured such that the function should never be called.

You are correct that logically you should be able to multiply a zero tile by a non-zero tile, but the result is known _a priory_. Thus there is no need to evaluate such a function when the result is known to be zero and TA does not store it.

If that assertion is hitting, there is definitely a bug somewhere. Can you provide a minimum failing example application?

**Comment by pchong90** [comment]
@justusc Thanks for the replying. This makes sense. I would like to make sure that this error is caused by "possible wrong" input that I provided. Unfortunately, It's hard for me to provide a small failing example other than my program. I already pushed the code to mpqc4 and provided an input for it as shown in issue [https://github.com/ValeevGroup/mpqc4/issues/37]. Let me know if you want me to test anything that would help solve this problem.

**Comment by justusc** [comment]
I ask for a minimal failing example to eliminate the possibility of errors in your code affecting TA behavior (_e.g._ a bad pointer write). The expression that it is failing on is fairly simple and covered in the unit tests. I think recreating the input tensors in the expression (TiledRange and SparseShape) should be sufficient to expose any bugs in TA. The tile data should not matter.

**Comment by pchong90** [comment]
I'm looking at expression.cpp. I noticed that it only tested expression with Dense Array. Do you have a test file where Sparse Array is used? If not, I will add Sparse Array test into expression.cpp

**Comment by justusc** [comment]
For the most part, I think I only tested dense expressions.

**Comment by pchong90** [comment]
I tried to model the failure in the test suite. However, it seems the error will occur only for specific data. Here I found one failing case for H2 and I print out the data as below. I will create a program later that use these specific data.

array a
```
0: [ [0,0], [1,4] ) { 0.00903500313851619 0.00791006318403205 -0.00620854389042444 -0.0136806688759872 }
1: [ [0,4], [1,8] ) { -0.000612070449010345 -0.00352370117644558 -0.000991230911095474 -0.00186978808953756 }
2: [ [0,8], [1,12] ) { 0.0500304778106021 0.00561605657542101 -0.0238541367850093 -0.00740893864550089 }
3: [ [0,12], [1,16] ) { -0.0189091562238754 -0.00172802238884289 -0.00366861913789014 -0.00209154387602903 }
4: [ [0,16], [1,20] ) { 0.000192648710559792 -0.00171539981398671 0.00393973005135415 -9.76439882924892e-05 }
5: [ [0,20], [1,24] ) { -0.00339248644834969 0.000336630152410405 0.000225646607181223 -0.0011502563489153 }
6: [ [0,24], [1,28] ) { 8.57445623750309e-05 0.000417265551201951 0.00190665236757716 4.211137059536e-05 }
7: [ [0,28], [1,32] ) { 0.000398735673727265 -0.000488623589801271 6.4319620374965e-16 -0.00122578800599979 }
8: [ [0,32], [1,36] ) { -0.000118113473654279 0.0020715203435194 0.000219878719297216 -5.76679806207421e-16 }
9: [ [0,36], [1,40] ) { 0.000662422538772495 -0.000353464856816049 -0.00111865862343783 -0.00345309211839291 }
10: [ [0,40], [1,44] ) { -0.00047033623988059 0.000972616886163973 -0.00117496807344 -0.000284538617421523 }
11: [ [0,44], [1,48] ) { 0.000231698672583168 -0.00151119449002147 9.36495898358796e-05 0.000801318813757354 }
12: [ [0,48], [1,52] ) { -0.000220195015110884 0.000723333149441981 0.000381688079141123 -0.00047882229233677 }
13: [ [0,52], [1,56] ) { -9.89124646718205e-16 -7.6099899701183e-05 0.000321858179003986 0.000127324171735022 }
14: [ [0,56], [1,61] ) { 0.000227478900554896 5.84519798947537e-16 0.000327775879334491 -0.000147873594163136 -0.000551769279675887 }
```

array b
```
4: [ [0,16], [1,20] ) { -0.941299730963643 -0.0950565490179549 -0.127699789054315 -0.558594969471144 }
5: [ [0,20], [1,24] ) { -0.086469938642225 -0.0923348512638083 -0.092334851263823 -0.124704572242564 }
6: [ [0,24], [1,28] ) { -0.121552481089887 -0.121552481089928 -0.440630266549898 -0.469381100005755 }
7: [ [0,28], [1,32] ) { -0.46938110000619 -0.0854161397971126 -0.0939371903013575 -0.0939042417570876 }
8: [ [0,32], [1,36] ) { -0.0854161397971157 -0.0938384139602803 -0.257876032553602 -0.275617131380275 }
9: [ [0,36], [1,40] ) { -0.274363089675321 -0.257876032553765 -0.271888932435775 -0.105861488172281 }
10: [ [0,40], [1,44] ) { -0.174126776186558 -0.682050628411282 -0.0861415710226029 -0.0923348512641737 }
11: [ [0,44], [1,48] ) { -0.0923348512641899 -0.12442676567033 -0.121552481090356 -0.121552481090401 }
12: [ [0,48], [1,52] ) { -0.419661276282393 -0.469381100009484 -0.469381100009843 -0.0854161397974653 }
13: [ [0,52], [1,56] ) { -0.0939371903017189 -0.0938780118061843 -0.0854161397974699 -0.093759878221004 }
14: [ [0,56], [1,61] ) { -0.257876032556864 -0.275617131382672 -0.273457994553032 -0.257876032557001 -0.269239641198587 }
```

failed expression
```
a("i,j") = a("i,j")*b("i,j");
```

**Comment by pchong90** [comment]
The error in MPQC4 is now solved. I set a wrong shape to an array. So the error won't get triggered now. Do we need to continue find the reason of assertion failed?

**Comment by justusc** [comment]
I was thinking that the error was coming from the shape. I do not think we need to investigate the source of the assertion as you have already found the error.

What did you do incorrectly? Perhaps I can add checks to catch a similar error in the future.

**Comment by pchong90** [comment]
I am using the shape of array A to construct array B. However, A and B don't have the same shape. So B is computed with the wrong shape and B become incorrect. I still don't understand why this will trigger the error though.

**Comment by justusc** [comment]
Code would help answer that question. Forcing an output shape could cause the error. You can see how the computation tasks are scheduled in https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/dist_eval/binary_eval.h#L134
